package com.nt.entity;
// Generated Nov 27, 2019 10:17:10 AM by Hibernate Tools 5.4.7.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private long eid;
	private String eadd;
	private String ename;
	private Double salary;

	public Employee() {
	}

	public Employee(long eid) {
		this.eid = eid;
	}

	public Employee(long eid, String eadd, String ename, Double salary) {
		this.eid = eid;
		this.eadd = eadd;
		this.ename = ename;
		this.salary = salary;
	}

	public long getEid() {
		return this.eid;
	}

	public void setEid(long eid) {
		this.eid = eid;
	}

	public String getEadd() {
		return this.eadd;
	}

	public void setEadd(String eadd) {
		this.eadd = eadd;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

}
