CREATE TABLE "SYSTEM"."INSURANCE_POLICY" 
   (	"POLICYID" NUMBER(10,0) NOT NULL ENABLE, 
	"POLICYNAME" VARCHAR2(20 BYTE), 
	"COMPANY" VARCHAR2(10 BYTE), 
	"POLICYTYPE" VARCHAR2(10 BYTE), 
	"TENURE" FLOAT(126), 
	 CONSTRAINT "INSURANCE_POLICY_PK" PRIMARY KEY ("POLICYID"))